### PR TITLE
Friendship

### PR DESCRIPTION
**Pull request by Alexoid1**
Create a model with associations and all requested features for friendships

Just show users not include the current users
Add friend list rerquests and accet friendship button
Add update frienship confirmed:true

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

There are some features missing in your application, let see:

* [x] A user should be able to reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] There should be a button to invite a user for friendship on single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [x] There are conditional statements in your view files, refactor them to their corresponding helper files. Use this [link](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) as a starter guide. 

That is it, when you are done with the changes submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Alexoid1 
### You have done well so far :clap: However, you have a few issues to solve:-
- [x] List articles associated with a user in their profile
- [ ] Add unit and integration tests, it's a requirement
- [x] There is also an error to the link that goes to a user profile
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

Great job, integration tests are working. 

* [x] But there is also the unit to implement, this entails testing your models' associations, validations and other methods you implemented.

When you are done with the changes submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Inyama Henry ```

**Review by Dandush03 — APPROVED** [review]
# Status :rocket: Approved :rocket: 
### Great work implementing all tests
### Make sure next time you fallow git-flow instructions, your PR should be Development -> Feature Branch. Do not create again a PR directly to your Master Branch.
> ### Next time your code will be marked as invalid
# :tophat: Happy Coding :computer: :nerd_face:

**Pull request closed without merging**
